on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy_prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel & Neon CLI
        run: npm i -g vercel neonctl
      - name: Install Dependencies
        run: npm ci
      - name: Get Neon Connection String
        run: echo "DATABASE_URL=$(neon connection-string --api-key ${{ secrets.NEON_API_KEY }} --project-id ${{ vars.NEON_PROJECT_ID }} --pooled main)" >> "$GITHUB_ENV"
      - name: Push Database Schema
        run: npx drizzle-kit push
      - name: Build Project Artifacts
        run: vercel build --prod --yes --token=${{ secrets.VERCEL_API_KEY }}
        env:
          NEXT_PUBLIC_GITHUB_REPOSITORY: ${{ github.repository }}
          NEXT_PUBLIC_GITHUB_REF: main
          NEXT_PUBLIC_NEON_BRANCH: main
          NEXT_PUBLIC_NEON_ONBOARDING_ID: ${{ vars.NEON_ONBOARDING_ID }}
          NEXT_PUBLIC_NEON_ONBOARDING_ORIGIN: ${{ vars.NEON_ONBOARDING_ORIGIN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_API_KEY }} --env DATABASE_URL=$DATABASE_URL
